{"declaration_or_definition_1":{"declaration_declarator_2":{"sign":"true","type":"int","limit":"empty","store":"empty"
},"compound_statement_8":{"block_9":{"declaration_or_definition_10":{"declaration_declarator_11":{"sign":"true","type":"int","limit":"empty","store":"empty"
},"initial_declarator_12":{"declarator_13":{"is_pointer":"0","direct_declarator_14":{"identifier_15":{"name":"a"
}
}
},"initializer_16":{"unary_expression_17":{"postfix_expression_18":{"primary_expression_19":{"constant_integer_number_1":"4"
}
},"is_sizeof":"false","unary_operator":"void"
}
}
}
}
},"block_20":{"switch_statement_21":{"unary_expression_22":{"postfix_expression_23":{"primary_expression_24":{"identifier_25":{"name":"a"
}
}
},"is_sizeof":"false","unary_operator":"void"
},"compound_statement_26":{"block_27":{"case_label_28":{"declaration_declarator_2":{"sign":"true","type":"int","limit":"empty","store":"empty"
}
}
},"block_29":{"expression_30":{"assignment_expression_35":{"assignment_type":"=","unary_expression_36":{"postfix_expression_37":{"primary_expression_38":{"constant_integer_number_1":"4"
}
},"is_sizeof":"false","unary_operator":"void"
},"unary_expression_31":{"postfix_expression_32":{"primary_expression_33":{"identifier_34":{"name":"a"
}
}
},"is_sizeof":"false","unary_operator":"void"
},"next_assign_34":{}
}
}
},"block_39":{"break_statement_40":{}
},"block_41":{"case_label_42":{"declarator_4":{"is_pointer":"0","direct_declarator_5":{"identifier_6":{"name":"main"
},"arguments_type_list_7":{}
}
}
}
},"block_43":{"expression_44":{"assignment_expression_49":{"assignment_type":"=","unary_expression_50":{"postfix_expression_51":{"primary_expression_52":{"constant_integer_number_1":"4"
}
},"is_sizeof":"false","unary_operator":"void"
},"unary_expression_45":{"postfix_expression_46":{"primary_expression_47":{"identifier_48":{"name":"a"
}
}
},"is_sizeof":"false","unary_operator":"void"
},"next_assign_48":{}
}
}
},"block_53":{"break_statement_54":{}
},"block_55":{"case_label_56":{"identifier_6":{"name":"main"
}
}
},"block_57":{"expression_58":{"assignment_expression_63":{"assignment_type":"=","unary_expression_64":{"postfix_expression_65":{"primary_expression_66":{"constant_integer_number_1":"4"
}
},"is_sizeof":"false","unary_operator":"void"
},"unary_expression_59":{"postfix_expression_60":{"primary_expression_61":{"identifier_62":{"name":"a"
}
}
},"is_sizeof":"false","unary_operator":"void"
},"next_assign_62":{}
}
}
},"block_67":{"break_statement_68":{}
}
}
}
},"block_70":{"declaration_or_definition_71":{"declaration_declarator_72":{"sign":"true","type":"int","limit":"empty","store":"empty"
},"initial_declarator_73":{"declarator_74":{"is_pointer":"0","direct_declarator_75":{"identifier_76":{"name":"b"
}
}
},"initializer_77":{"unary_expression_78":{"postfix_expression_79":{"primary_expression_80":{"identifier_81":{"name":"a"
}
}
},"is_sizeof":"false","unary_operator":"void"
}
}
}
}
},"block_82":{"return_statement_83":{"unary_expression_84":{"postfix_expression_85":{"primary_expression_86":{"identifier_87":{"name":"b"
}
}
},"is_sizeof":"false","unary_operator":"void"
}
}
}
},"initial_declarator_3":{"declarator_4":{"is_pointer":"0","direct_declarator_5":{"identifier_6":{"name":"main"
},"arguments_type_list_7":{}
}
}
}
}
}