{"declaration_or_definition_1":{"declaration_declarator_2":{"sign":"true","type":"int","limit":"empty","store":"empty"
},"compound_statement_8":{"block_9":{"declaration_or_definition_10":{"declaration_declarator_11":{"sign":"true","type":"int","limit":"empty","store":"empty"
},"initial_declarator_12":{"declarator_13":{"is_pointer":"0","direct_declarator_14":{"identifier_15":{"name":"a"
},"array_declarator_16":{"unary_expression_17":{"postfix_expression_18":{"primary_expression_19":{"constant_integer_number_1":"3"
}
},"is_sizeof":"false","unary_operator":"void"
}
}
}
}
}
}
},"block_20":{"declaration_or_definition_21":{"declaration_declarator_22":{"sign":"true","type":"int","limit":"empty","store":"empty"
},"initial_declarator_23":{"declarator_24":{"is_pointer":"0","direct_declarator_25":{"identifier_26":{"name":"b"
},"array_declarator_27":{"unary_expression_28":{"postfix_expression_29":{"primary_expression_30":{"constant_integer_number_1":"3"
}
},"is_sizeof":"false","unary_operator":"void"
},"array_declarator_31":{"unary_expression_32":{"postfix_expression_33":{"primary_expression_34":{"constant_integer_number_1":"3"
}
},"is_sizeof":"false","unary_operator":"void"
}
}
}
}
}
}
}
},"block_35":{"declaration_or_definition_36":{"declaration_declarator_37":{"sign":"true","type":"int","limit":"empty","store":"empty"
},"initial_declarator_38":{"declarator_39":{"is_pointer":"0","direct_declarator_40":{"identifier_41":{"name":"c"
},"array_declarator_42":{"unary_expression_43":{"postfix_expression_44":{"primary_expression_45":{"constant_integer_number_1":"3"
}
},"is_sizeof":"false","unary_operator":"void"
},"array_declarator_46":{"unary_expression_47":{"postfix_expression_48":{"primary_expression_49":{"constant_integer_number_1":"3"
}
},"is_sizeof":"false","unary_operator":"void"
},"array_declarator_50":{"unary_expression_51":{"postfix_expression_52":{"primary_expression_53":{"constant_integer_number_1":"3"
}
},"is_sizeof":"false","unary_operator":"void"
},"array_declarator_54":{"unary_expression_55":{"postfix_expression_56":{"primary_expression_57":{"constant_integer_number_1":"3"
}
},"is_sizeof":"false","unary_operator":"void"
}
}
}
}
}
}
}
}
}
},"block_58":{"expression_59":{"assignment_expression_72":{"assignment_type":"=","binary_expression_93":{"operator":"+","unary_expression_73":{"postfix_expression_74":{"postfix_operator_77":{"unary_expression_78":{"postfix_expression_79":{"primary_expression_80":{"constant_integer_number_1":"3"
}
},"is_sizeof":"false","unary_operator":"void"
},"postfix_operator_81":{"unary_expression_82":{"postfix_expression_83":{"primary_expression_84":{"constant_integer_number_1":"3"
}
},"is_sizeof":"false","unary_operator":"void"
},"postfix_operator_85":{"unary_expression_86":{"postfix_expression_87":{"primary_expression_88":{"constant_integer_number_1":"3"
}
},"is_sizeof":"false","unary_operator":"void"
},"postfix_operator_89":{"unary_expression_90":{"postfix_expression_91":{"primary_expression_92":{"constant_integer_number_1":"3"
}
},"is_sizeof":"false","unary_operator":"void"
}
}
}
}
},"primary_expression_75":{"identifier_76":{"name":"c"
}
}
},"is_sizeof":"false","unary_operator":"void"
},"unary_expression_94":{"postfix_expression_95":{"postfix_operator_98":{"unary_expression_99":{"postfix_expression_100":{"primary_expression_101":{"constant_integer_number_1":"3"
}
},"is_sizeof":"false","unary_operator":"void"
}
},"primary_expression_96":{"identifier_97":{"name":"a"
}
}
},"is_sizeof":"false","unary_operator":"void"
}
},"unary_expression_60":{"postfix_expression_61":{"postfix_operator_64":{"unary_expression_65":{"postfix_expression_66":{"primary_expression_67":{"constant_integer_number_1":"3"
}
},"is_sizeof":"false","unary_operator":"void"
},"postfix_operator_68":{"unary_expression_69":{"postfix_expression_70":{"primary_expression_71":{"constant_integer_number_1":"3"
}
},"is_sizeof":"false","unary_operator":"void"
}
}
},"primary_expression_62":{"identifier_63":{"name":"b"
}
}
},"is_sizeof":"false","unary_operator":"void"
},"next_assign_63":{}
}
}
},"block_102":{"return_statement_103":{"unary_expression_104":{"postfix_expression_105":{"postfix_operator_108":{"unary_expression_109":{"postfix_expression_110":{"primary_expression_111":{"constant_integer_number_1":"3"
}
},"is_sizeof":"false","unary_operator":"void"
},"postfix_operator_112":{"unary_expression_113":{"postfix_expression_114":{"primary_expression_115":{"constant_integer_number_1":"3"
}
},"is_sizeof":"false","unary_operator":"void"
}
}
},"primary_expression_106":{"identifier_107":{"name":"b"
}
}
},"is_sizeof":"false","unary_operator":"void"
}
}
}
},"initial_declarator_3":{"declarator_4":{"is_pointer":"0","direct_declarator_5":{"identifier_6":{"name":"main"
},"arguments_type_list_7":{}
}
}
}
}
}