{"declaration_or_definition_1":{"declaration_declarator_2":{"sign":"true","type":"int","limit":"empty","store":"empty"
},"compound_statement_8":{"block_9":{"declaration_or_definition_10":{"declaration_declarator_11":{"sign":"true","type":"int","limit":"empty","store":"empty"
},"initial_declarator_12":{"declarator_13":{"is_pointer":"0","direct_declarator_14":{"identifier_15":{"name":"a"
}
}
},"initializer_16":{"unary_expression_17":{"postfix_expression_18":{"primary_expression_19":{"constant_integer_number_1":"1"
}
},"is_sizeof":"false","unary_operator":"void"
}
}
}
}
},"block_20":{"declaration_or_definition_21":{"declaration_declarator_22":{"sign":"true","type":"long_long_int","limit":"empty","store":"empty"
},"initial_declarator_23":{"declarator_24":{"is_pointer":"0","direct_declarator_25":{"identifier_26":{"name":"b"
}
}
},"initializer_27":{"unary_expression_28":{"postfix_expression_29":{"primary_expression_30":{"constant_integer_number_1":"1"
}
},"is_sizeof":"false","unary_operator":"void"
}
}
}
}
},"block_31":{"declaration_or_definition_32":{"declaration_declarator_33":{"sign":"true","type":"int","limit":"empty","store":"empty"
},"initial_declarator_34":{"declarator_35":{"is_pointer":"0","direct_declarator_36":{"identifier_37":{"name":"c"
}
}
},"initializer_38":{"binary_expression_43":{"operator":"+","unary_expression_39":{"postfix_expression_40":{"primary_expression_41":{"identifier_42":{"name":"a"
}
}
},"is_sizeof":"false","unary_operator":"void"
},"unary_expression_44":{"postfix_expression_45":{"primary_expression_46":{"identifier_47":{"name":"b"
}
}
},"is_sizeof":"false","unary_operator":"void"
}
}
}
}
}
},"block_48":{"declaration_or_definition_49":{"declaration_declarator_50":{"sign":"false","type":"int","limit":"empty","store":"empty"
},"initial_declarator_51":{"declarator_52":{"is_pointer":"0","direct_declarator_53":{"identifier_54":{"name":"e"
}
}
}
}
}
},"block_55":{"expression_56":{"assignment_expression_61":{"assignment_type":"=","binary_expression_76":{"operator":"+","binary_expression_71":{"operator":"+","binary_expression_66":{"operator":"/","unary_expression_62":{"postfix_expression_63":{"primary_expression_64":{"identifier_65":{"name":"c"
}
}
},"is_sizeof":"false","unary_operator":"void"
},"unary_expression_67":{"postfix_expression_68":{"primary_expression_69":{"identifier_70":{"name":"a"
}
}
},"is_sizeof":"false","unary_operator":"void"
}
},"unary_expression_72":{"postfix_expression_73":{"primary_expression_74":{"identifier_75":{"name":"b"
}
}
},"is_sizeof":"false","unary_operator":"void"
}
},"binary_expression_81":{"operator":"/","unary_expression_77":{"postfix_expression_78":{"primary_expression_79":{"identifier_80":{"name":"a"
}
}
},"is_sizeof":"false","unary_operator":"void"
},"unary_expression_82":{"postfix_expression_83":{"primary_expression_84":{"identifier_85":{"name":"b"
}
}
},"is_sizeof":"false","unary_operator":"void"
}
}
},"unary_expression_57":{"postfix_expression_58":{"primary_expression_59":{"identifier_60":{"name":"e"
}
}
},"is_sizeof":"false","unary_operator":"void"
},"next_assign_60":{}
}
}
},"block_86":{"return_statement_87":{"unary_expression_88":{"postfix_expression_89":{"primary_expression_90":{"identifier_91":{"name":"e"
}
}
},"is_sizeof":"false","unary_operator":"void"
}
}
}
},"initial_declarator_3":{"declarator_4":{"is_pointer":"0","direct_declarator_5":{"identifier_6":{"name":"main"
},"arguments_type_list_7":{}
}
}
}
}
}