@startjson
{"Block":{"statement-0":{"FuncDef":{"name":"main","argument_type_list":[],"body":{"Block":{"statement-0":{"VarDef":{"identifier:":"a","type":"int32","initializer":{"ConstantInt":{"value":"1","negative":"false" } } } },"statement-1":{"VarDef":{"identifier:":"b","type":"int32","initializer":{"ConstantInt":{"value":"3","negative":"false" } } } },"statement-2":{"DoWhileStatement":{"expr":{"Expr":{"operator":"<","l_expr":{"Var":{"identifier":"a","type":{"type":"int32" } } },"r_expr":{"ConstantInt":{"value":"4","negative":"false" } } } },"do_while_body":{"Block":{"statement-0":{"Expr":{"operator":"+=","l_expr":{"Var":{"identifier":"b","type":{"type":"int32" } } },"r_expr":{"Expr":{"operator":"-=","l_expr":{"Var":{"identifier":"a","type":{"type":"int32" } } },"r_expr":{"ConstantInt":{"value":"3","negative":"false" } } } } } } } } } },"statement-3":{"ReturnStatement":{"ConstantInt":{"value":"0","negative":"false" } } } } } } } } }
@endjson