@startjson
{"Block":{"statement-0":{"FuncDef":{"name":"main","argument_type_list":[],"body":{"Block":{"statement-0":{"VarDef":{"identifier:":"a","type":"int32" } },"statement-1":{"VarDef":{"identifier:":"b","type":"int32","initializer":{"ConstantInt":{"value":"1","negative":"false" } } } },"statement-2":{"VarDef":{"identifier:":"c","PointerType":{"element_type":{"type":"int32" } } } },"statement-3":{"VarDef":{"identifier:":"d","type":"double","initializer":{"ConstantFloat":{"value":"3.21","negative":"false" } } } },"statement-4":{"VarDef":{"identifier:":"e","type":"double" } },"statement-5":{"VarDef":{"identifier:":"f","type":"int64" } },"statement-6":{"VarDef":{"identifier:":"g","type":"uint32","initializer":{"ConstantInt":{"value":"2","negative":"false" } } } },"statement-7":{"ReturnStatement":{"ConstantInt":{"value":"0","negative":"false" } } } } } } } } }
@endjson